export const UI_EDIT_USER_PROFILE = '[PROFILE] UI_EDIT_USER_PROFILE';
export const UPDATE_PROFILE_CHANGE_NAME = '[PROFILE] UPDATE_PROFILE_CHANGE_NAME';
export const UPDATE_PROFILE_USER_START = '[PROFILE] UPDATE_PROFILE_USER_START';
export const UPDATE_PROFILE_USER_SUCCESS = '[PROFILE] UPDATE_PROFILE_USER_SUCCESS';
export const UPDATE_PROFILE_USER_FAIL = '[PROFILE] UPDATE_PROFILE_USER_FAIL';
export const CANCEL_UPDATE_PROFILE_USER = '[PROFILE] CANCEL_UPDATE_PROFILE_USER';

